packages:
  - "packages/*"
  - "apps/*"

allowBuilds:
  "@bufbuild/buf": true
  "@swc/core": true
  bufferutil: true
  core-js: true
  esbuild: true
  exifreader: true
  msw: true
  protobufjs: true
  sharp: true

resolutionMode: "highest"
minimumReleaseAge: 1440
minimumReleaseAgeIgnoreMissingTime: true
minimumReleaseAgeExclude:
  - si2pem-reader@0.3.6
  - "@btsearch/rf-engine@0.1.3"
  - "@btsearch/rf-engine-win32-x64-msvc@0.1.3"
  - "@btsearch/rf-engine-darwin-x64@0.1.3"
  - "@btsearch/rf-engine-darwin-arm64@0.1.3"
  - "@btsearch/rf-engine-linux-x64-gnu@0.1.3"
  - "@btsearch/rf-engine-linux-arm64-gnu@0.1.3"
